#!/usr/bin/with-contenv sh

# set crontab
crontab -u abc /defaults/rclone_cron

# permissions
chown -R abc:abc \
	/app
chown abc:abc \
	/config/.rclone.conf
chmod +x /app/rclone.sh

# run first time
exec \
	s6-setuidgid abc /app/rclone.sh