#!/usr/bin/with-contenv sh

# set crontab
crontab -u abc /defaults/rclone_cron

# permissions
chown -R abc:abc \
	/app
chown abc:abc \
	/config/.rclone.conf
chmod +x \
	/app/rclone.sh
chmod 777 \
	/var/lock